### ISSUE TITLE
Criar estrutura do plugin

### ISSUE THREAD

**Issue by rodrigondec** [imobanco/WooCommerce-Imobanco#3]
# Resumo
Provavelmente existe um boilerplate para plugin WP.

# Tarefa
- [x] Subir essa estrutura
- [x] Colocar o volume do nosso código no container

# Volume no docker-compose
Temos que dar o bind no código do plugin para a pasta de plugins do container do docker-compose. Isso pode ser feito de maneira similar a:

```
  wordpress:
    image: docker.io/bitnami/wordpress:5-debian-10
    ports:
      - "80:8080"
      - "443:8443"
    volumes:
      - wordpress_data:/bitnami/wordpress
      - .src:/bitnami/wordpress/wp-plugins/wp-zoop-gateway
    depends_on:
      - mariadb
    env_file: .env
```
